name: SonarCloud
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}-quality-sonar
  cancel-in-progress: true

permissions:
  packages: read
  id-token: write
  contents: read

jobs:
  sonarcloud:
    if: ${{ github.event.pull_request.draft == false && github.actor != 'dependabot[bot]' }}
    name: Run SonarCloud Job
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v4.0.0

      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v4.0.0
        with:
          node-version: 20.13.0

      - name: Run Tests for Events
        working-directory: ./events
        run: |
          npm ci
          npm test
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Tests for Logging
        working-directory: ./logging
        run: |
          npm ci
          npm test
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@713881670b6b3676cda39549040e2d88c70d582e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
