# Publish logging and events packages
name: Publish
on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        default: 'Logging'
        description: Please select the package to publish
        type: choice
        options:
          - Logging
          - Events
          - Ticf-api
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v4.0.0
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v4.0.0
        with:
          node-version: 20.13.0
      - run: |
          case "${{github.event.inputs.environment}}" in
            'Logging')
              echo "Publishing Logging Package"
              cd ./logging
              ;;   
            'Events')
              echo "Publishing Events Package"
              cd ./events
              ;;
            'Ticf-api')
              echo "Publishing Ticf-api Package"
              cd ./ticf-api
              ;;
          esac

          echo @govuk-one-login:https://npm.pkg.github.com/ > .npmrc
          echo '//npm.pkg.github.com/:_authToken=${NPM_TOKEN}' >> .npmrc
          npm ci --ignore-scripts
          npm exec --ignore-scripts --no -- tsc
          npm test
          npm publish
        shell: bash
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
